import PptxGenJS from 'pptxgenjs';
import fetch from 'node-fetch';

const FETCH_TIMEOUT_MS = 10000;

const COLORS = {
  primary: '2563EB',
  secondary: '0F172A',
  text: '334155',
  light: 'F8FAFC',
  border: 'E2E8F0',
  white: 'FFFFFF',
  muted: '64748B',
};

const fetchBuffer = async (url) => {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), FETCH_TIMEOUT_MS);

  try {
    const res = await fetch(url, { signal: controller.signal });
    if (!res.ok) return null;

    const contentType = res.headers.get('content-type') || '';
    if (!contentType.startsWith('image/')) return null;

    const arrayBuffer = await res.arrayBuffer();
    return Buffer.from(arrayBuffer).toString('base64');
  } catch {
    return null;
  } finally {
    clearTimeout(timer);
  }
};

const getImage = async (query = 'technology') => {
  const seed = encodeURIComponent(query);
  return fetchBuffer(`https://picsum.photos/seed/${seed}/800/400`);
};

export const generatePpt = async (data) => {
  const ppt = new PptxGenJS();

  // meta
  ppt.layout = 'LAYOUT_WIDE';
  ppt.author = 'Cortex AI';
  ppt.title = data.title;
  ppt.subject = data.title;
  ppt.company = 'Cortex AI';

  await addCover(ppt, data);

  for (let i = 0; i < data.slides.length; i++) {
    await addContentSlide(ppt, data.slides[i], i + 1, data.slides.length);
  }

  addThankYou(ppt);

  // return buffer
  return ppt.write('nodebuffer');
};

const addCover = async (ppt, data) => {
  const slide = ppt.addSlide();

  slide.background = { color: COLORS.primary };

  slide.addText(data.title, {
    x: 1,
    y: 2,
    w: 11,
    h: 1,
    fontSize: 36,
    bold: true,
    color: COLORS.white,
    align: 'center',
  });

  if (data.subtitle) {
    slide.addText(data.subtitle, {
      x: 1,
      y: 3,
      w: 11,
      fontSize: 16,
      color: 'DBEAFE',
      align: 'center',
    });
  }

  const img = await getImage(data.title);
  if (img) {
    slide.addImage({
      data: `data:image/jpeg;base64,${img}`,
      x: 3,
      y: 4,
      w: 7,
      h: 2.5,
    });
  }

  slide.addText('Generated by Cortex AI', {
    x: 0,
    y: 6.8,
    w: 13.3,
    align: 'center',
    fontSize: 10,
    color: 'BFDBFE',
  });
};

const addContentSlide = async (ppt, section, page, total) => {
  const slide = ppt.addSlide();

  slide.background = { color: COLORS.white };

  slide.addText(section.title, {
    x: 0.7,
    y: 0.5,
    w: 12,
    fontSize: 26,
    bold: true,
    color: COLORS.secondary,
  });

  slide.addShape(ppt.ShapeType.rect, {
    x: 0.7,
    y: 1.1,
    w: 2,
    h: 0.08,
    fill: { color: COLORS.primary },
  });

  const points = section.points || [];
  const mid = Math.ceil(points.length / 2);

  const col1 = points.slice(0, mid);
  const col2 = points.slice(mid);

  slide.addText(col1.map((p) => `• ${p}`).join('\n'), {
    x: 0.7,
    y: 1.5,
    w: 5.5,
    fontSize: 14,
    color: COLORS.text,
  });

  slide.addText(col2.map((p) => `• ${p}`).join('\n'), {
    x: 6.5,
    y: 1.5,
    w: 5.5,
    fontSize: 14,
    color: COLORS.text,
  });

  const chartData = [
    {
      name: section.title,
      labels: points.map((_, i) => `P${i + 1}`),
      values: points.map(() => Math.floor(Math.random() * 100)),
    },
  ];

  slide.addChart(ppt.ChartType.bar, chartData, { x: 1, y: 4, w: 5.5, h: 2.5 });

  const img = await getImage(section.title);
  if (img) {
    slide.addImage({
      data: `data:image/jpeg;base64,${img}`,
      x: 7,
      y: 4,
      w: 5,
      h: 2.5,
    });
  }

  slide.addText(`${page}/${total}`, {
    x: 12,
    y: 6.8,
    fontSize: 10,
    color: COLORS.muted,
  });
};

const addThankYou = (ppt) => {
  const slide = ppt.addSlide();

  slide.background = { color: COLORS.secondary };

  slide.addText('Thank You', {
    x: 1,
    y: 2.5,
    w: 11,
    fontSize: 40,
    bold: true,
    align: 'center',
    color: COLORS.white,
  });

  slide.addText('Questions?', {
    x: 1,
    y: 3.5,
    w: 11,
    fontSize: 18,
    align: 'center',
    color: '94A3B8',
  });
};
