import PDFDocument from 'pdfkit';
import fetch from 'node-fetch';

const FETCH_TIMEOUT_MS = 10000;

const COLORS = {
  primary: '#2563EB',
  secondary: '#0F172A',
  text: '#334155',
  white: '#FFFFFF',
  muted: '#64748B',
  accent: '#DBEAFE',
  gray: '#94A3B8',
};

const fetchBuffer = async (url) => {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), FETCH_TIMEOUT_MS);
  try {
    const res = await fetch(url, { signal: controller.signal });
    if (!res.ok) return null;
    const contentType = res.headers.get('content-type') || '';
    if (!contentType.startsWith('image/')) return null;
    const arrayBuffer = await res.arrayBuffer();
    return Buffer.from(arrayBuffer);
  } catch {
    return null;
  } finally {
    clearTimeout(timer);
  }
};

const getImageBuffer = async (query = 'technology') => {
  const seed = encodeURIComponent(query);
  return fetchBuffer(`https://picsum.photos/seed/${seed}/800/400`);
};

const getChartBuffer = async (slide) => {
  const points = slide.points || [];
  if (!points.length) return null;

  const labels = points.map((_, i) => `P${i + 1}`);
  const values = points.map(() => Math.floor(Math.random() * 100));

  const chartConfig = {
    type: 'bar',
    data: {
      labels,
      datasets: [{ label: slide.title || 'Data', data: values }],
    },
  };

  const url = `https://quickchart.io/chart?c=${encodeURIComponent(
    JSON.stringify(chartConfig)
  )}`;
  return fetchBuffer(url);
};

const safeImage = (doc, buffer, ...args) => {
  if (!buffer) return;
  try {
    doc.image(buffer, ...args);
  } catch (err) {
    console.error('Failed to embed image in PDF:', err.message);
  }
};

export const generatePresentationPdf = async (data) => {
  return new Promise(async (resolve, reject) => {
    try {
      // Widescreen 16:9 — 960 x 540 points
      const doc = new PDFDocument({ size: [960, 540] });
      const chunks = [];

      doc.on('data', (c) => chunks.push(c));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      /** ================= COVER SLIDE ================= */
      doc.rect(0, 0, 960, 540).fill(COLORS.primary);

      doc
        .fillColor(COLORS.white)
        .fontSize(36)
        .text(data.title, 50, 160, { align: 'center', width: 860 });

      if (data.subtitle) {
        doc
          .fillColor(COLORS.accent)
          .fontSize(16)
          .text(data.subtitle, 50, 230, { align: 'center', width: 860 });
      }

      const coverImg = await getImageBuffer(data.title);
      if (coverImg) {
        safeImage(doc, coverImg, 280, 280, { fit: [400, 180] });
      }

      doc
        .fontSize(10)
        .fillColor('#BFDBFE')
        .text('Generated by Cortex AI', 50, 510, {
          align: 'center',
          width: 860,
        });

      /** ================= CONTENT SLIDES ================= */
      const slides = data.slides || [];
      for (let i = 0; i < slides.length; i++) {
        const slide = slides[i];
        doc.addPage();

        // White background
        doc.rect(0, 0, 960, 540).fill(COLORS.white);

        // Title
        doc
          .fillColor(COLORS.secondary)
          .fontSize(26)
          .text(slide.title, 50, 35, { width: 860 });

        // Accent bar
        doc.rect(50, 75, 120, 5).fill(COLORS.primary);

        // Bullet points — two columns
        const points = slide.points || [];
        const mid = Math.ceil(points.length / 2);
        const col1 = points.slice(0, mid);
        const col2 = points.slice(mid);

        const bulletText = (pts) => pts.map((p) => `• ${p}`).join('\n');

        doc
          .fontSize(13)
          .fillColor(COLORS.text)
          .text(bulletText(col1), 50, 100, { width: 400, lineGap: 6 });

        if (col2.length) {
          doc.text(bulletText(col2), 480, 100, { width: 400, lineGap: 6 });
        }

        // Chart
        const chart = await getChartBuffer(slide);
        if (chart) {
          safeImage(doc, chart, 50, 290, { fit: [400, 210] });
        }

        // Image
        const img = await getImageBuffer(slide.title);
        if (img) {
          safeImage(doc, img, 480, 290, { fit: [430, 210] });
        }

        // Page number
        doc
          .fontSize(10)
          .fillColor(COLORS.muted)
          .text(`${i + 1}/${slides.length}`, 850, 515, {
            align: 'right',
            width: 60,
          });
      }

      /** ================= THANK YOU SLIDE ================= */
      doc.addPage();
      doc.rect(0, 0, 960, 540).fill(COLORS.secondary);

      doc
        .fillColor(COLORS.white)
        .fontSize(40)
        .text('Thank You', 50, 200, { align: 'center', width: 860 });

      doc
        .fontSize(18)
        .fillColor(COLORS.gray)
        .text('Questions?', 50, 280, { align: 'center', width: 860 });

      doc.end();
    } catch (err) {
      reject(err);
    }
  });
};
