import PDFDocument from 'pdfkit';
import fetch from 'node-fetch';

const FETCH_TIMEOUT_MS = 10000;

const fetchBuffer = async (url) => {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), FETCH_TIMEOUT_MS);
  try {
    const res = await fetch(url, { signal: controller.signal });
    if (!res.ok) return null;

    const contentType = res.headers.get('content-type') || '';
    if (!contentType.startsWith('image/')) return null;

    const arrayBuffer = await res.arrayBuffer();
    return Buffer.from(arrayBuffer);
  } catch {
    return null;
  } finally {
    clearTimeout(timer);
  }
};

const getImageBuffer = async (query = 'technology') => {
  const seed = encodeURIComponent(query);
  return fetchBuffer(`https://picsum.photos/seed/${seed}/800/400`);
};

const getChartBuffer = async (section) => {
  const labels = section.points.map((_, i) => `P${i + 1}`);
  const values = section.points.map(() => Math.floor(Math.random() * 100));

  const chartConfig = {
    type: 'bar',
    data: {
      labels,
      datasets: [
        {
          label: section.heading,
          data: values,
        },
      ],
    },
  };

  const url = `https://quickchart.io/chart?c=${encodeURIComponent(
    JSON.stringify(chartConfig)
  )}`;

  return fetchBuffer(url);
};

const safeImage = (doc, buffer, ...args) => {
  if (!buffer) return;
  try {
    doc.image(buffer, ...args);
  } catch (err) {
    console.error('Failed to embed image in PDF:', err.message);
  }
};

export const generatePdf = async (data) => {
  return new Promise(async (resolve, reject) => {
    try {
      const doc = new PDFDocument({ size: 'A4', margin: 50 });

      const chunks = [];
      doc.on('data', (c) => chunks.push(c));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      /** ================= COVER PAGE ================= */
      doc.rect(0, 0, doc.page.width, doc.page.height).fill('#0f172a');

      doc
        .fillColor('#ffffff')
        .fontSize(32)
        .text(data.title, 50, 200, { align: 'center' });

      if (data.subtitle) {
        doc
          .moveDown()
          .fontSize(14)
          .fillColor('#cbd5f5')
          .text(data.subtitle, { align: 'center' });
      }

      const coverImg = await getImageBuffer(data.title);
      safeImage(doc, coverImg, 100, 350, { fit: [400, 200] });

      doc.addPage();

      /** ================= CONTENT ================= */
      for (const section of data.sections || []) {
        doc.addPage();

        // Section Title
        doc.fillColor('#111827').fontSize(20).text(section.heading);

        doc.moveDown();

        /** -------- MULTI COLUMN TEXT -------- */
        doc
          .fontSize(11)
          .fillColor('#374151')
          .text(section.points.map((p) => `• ${p}`).join('\n\n'), {
            columns: 2,
            columnGap: 20,
            align: 'justify',
          });

        doc.moveDown(2);

        /** -------- TABLE -------- */
        doc.fontSize(13).fillColor('#111827').text('Summary Table');
        doc.moveDown(0.5);

        section.points.forEach((p, i) => {
          doc
            .fontSize(11)
            .fillColor('#374151')
            .text(`Point ${i + 1}: `, { continued: true, width: 100 })
            .text(p);
        });

        doc.moveDown(1);

        /** -------- CHART -------- */
        const chart = await getChartBuffer(section);
        if (chart) {
          safeImage(doc, chart, { fit: [450, 250], align: 'center' });
          doc.moveDown();
        }

        /** -------- IMAGE -------- */
        const img = await getImageBuffer(section.heading);
        safeImage(doc, img, { fit: [450, 250], align: 'center' });

        doc.moveDown(2);
      }

      /** ================= FOOTER ================= */
      doc.fontSize(10).fillColor('#9CA3AF').text('Generated by Cortex AI', {
        align: 'center',
      });

      doc.end();
    } catch (err) {
      reject(err);
    }
  });
};
